python run_nen.py \
  --model_type=bert \
  --model_name_or_path=./data/model_data/biobert-base-cased-v1.1 \
  --do_train \
  --do_eval \
  --do_lower_case \
  --loss_type=ce \
  --data_dir=./datasets/CDR/ \
  --train_max_seq_length=128 \
  --eval_max_seq_length=512 \
  --per_gpu_train_batch_size=16 \
  --per_gpu_eval_batch_size=64 \
  --learning_rate=3e-5 \
  --num_train_epochs=20 \
  --logging_steps=-1 \
  --save_steps=-1 \
  --output_dir=./outputs \
  --overwrite_output_dir \
  --seed=777
  --dataset=cdr
  --task_name=nen
  --markup=bo
  